# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(593, 856)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(290, 360, 211, 321))
        self.label.setText("")
        self.label.setOpenExternalLinks(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 571, 841))
        self.label_2.setStyleSheet("background-image: url(:/img/back2.jpg);\n"
"border-radius: 30px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(40, 50, 511, 741))
        self.label_3.setStyleSheet("background-color: rgba(8, 8, 8,130);\n"
"border-radius: 20px;\n"
"\n"
"")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(210, 100, 211, 101))
        self.label_4.setStyleSheet("color: rgb(216, 216, 216);\n"
"font: 75 36pt \"MS Shell Dlg 2\";\n"
"")
        self.label_4.setObjectName("label_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(140, 470, 371, 71))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.lineEdit_4.setStyleSheet("QLineEdit {\n"
"    font: 75 20pt \"MS Shell Dlg 2\";\n"
"    background-color:rgba(0,0,0,0);\n"
"    border: none;\n"
"    border-bottom: 2px solid #d5d5d5;\n"
"    padding-left:10px;\n"
"    color:#FFF;\n"
"    font-size: 24px;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border-bottom: 4px solid #fff;\n"
"    cursor:pointer;\n"
"    \n"
"\n"
"}")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.VisualMoveStyle)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setGeometry(QtCore.QRect(60, 375, 40, 40))
        self.label_5.setStyleSheet("border-image: url(:/img/user.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=Form)
        self.label_6.setGeometry(QtCore.QRect(60, 502, 40, 40))
        self.label_6.setStyleSheet("border-image: url(:/img/password.png);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setGeometry(QtCore.QRect(140, 670, 306, 91))
        self.pushButton.setStyleSheet("QPushButton{ \n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color:#fff;\n"
"    background-color: qradialgradient(spread:pad,cx:0.5,cy:0.5, radius: 0.5,fx:0.5, fy:0.5, stop:0, rgba(0,0,0,255), stop:0.00995025 rgba(0,0,0,20), stop:1 rgba(0,0,0,111));\n"
"    border:2px outset #d5d5d5;\n"
"    border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 4px inset cyan;\n"
"    color:cyan;\n"
"    transition: 2s;\n"
"    \n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border: 6px outset cyan;\n"
"    color:cyan;\n"
"    font:30px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(140, 360, 371, 71))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.lineEdit_5.setStyleSheet("QLineEdit {\n"
"    font: 75 20pt \"MS Shell Dlg 2\";\n"
"    background-color:rgba(0,0,0,0);\n"
"    border: none;\n"
"    border-bottom: 2px solid #d5d5d5;\n"
"    padding-left:10px;\n"
"    color:#FFF;\n"
"    font-size: 24px;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border-bottom: 4px solid #fff;\n"
"    cursor:pointer;\n"
"    \n"
"\n"
"}")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.VisualMoveStyle)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_7 = QtWidgets.QLabel(parent=Form)
        self.label_7.setGeometry(QtCore.QRect(180, 580, 191, 51))
        self.label_7.setStyleSheet("color: rgb(234, 234, 234);\n"
"color: rgb(171, 171, 171);\n"
"font: 8pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_2.setGeometry(QtCore.QRect(320, 580, 111, 51))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"color: rgb(255, 0, 0);\n"
"background-color:transparent;\n"
"border:none;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"font:16px;\n"
"font-style:bold;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: #d5d5d5;\n"
"color: red;\n"
"border:1px outset #d5d5d5;\n"
"border-radius:15px;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "Log In"))
        self.lineEdit_4.setPlaceholderText(_translate("Form", "Password"))
        self.pushButton.setText(_translate("Form", "Entrar"))
        self.lineEdit_5.setPlaceholderText(_translate("Form", "User Name"))
        self.label_7.setText(_translate("Form", "Esqueceu a senha ? "))
        self.pushButton_2.setText(_translate("Form", "Clique Aqui !"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
